package medora.repository;

import medora.models.domain.Admin;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

public interface AdminRepository extends JpaRepository<Admin, Long> {

    // adminId is NOT auto-generated by the database (supplied by the application),
    // so callers must compute the next free ID before saving a new Admin.
    @Query("SELECT COALESCE(MAX(e.adminId), 0) FROM Admin e")
    Long findMaxAdminId();
}

