package medora.repository;

import medora.models.domain.LabTechnician;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

public interface LabTechnicianRepository extends JpaRepository<LabTechnician, Long> {

    // technicianId is NOT auto-generated by the database (supplied by the application),
    // so callers must compute the next free ID before saving a new LabTechnician.
    @Query("SELECT COALESCE(MAX(e.technicianId), 0) FROM LabTechnician e")
    Long findMaxTechnicianId();
}
