package medora.repository;

import medora.models.domain.Patient;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.Optional;

public interface PatientRepository extends JpaRepository<Patient, Long> {

    // patientId is NOT auto-generated by the database (supplied by the application),
    // so callers must compute the next free ID before saving a new Patient.
    @Query("SELECT COALESCE(MAX(e.patientId), 0) FROM Patient e")
    Long findMaxPatientId();

    // Login lookup: find the patient profile linked to a given user account
    // (Patient.user_id is the foreign key, the reverse of Users->Patient)
    Optional<Patient> findByUserUserId(Long userId);

    // UC004 – View Patient Profile
    // Find patient by EMBG (unique identifier)
    Optional<Patient> findByEmbg(String embg);

    // Find patient by email for login/contact purposes
    Optional<Patient> findByEmailAddress(String emailAddress);

    // UC026 – Helper for medical record search by patient name
    @Query("""
        SELECT p FROM Patient p
        WHERE LOWER(p.firstName) LIKE LOWER(CONCAT('%', :name, '%'))
           OR LOWER(p.lastName) LIKE LOWER(CONCAT('%', :name, '%'))
    """)
    List<Patient> findByNameContainingIgnoreCase(@Param("name") String name);
}