package medora.repository;

import medora.models.domain.Procedure;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

public interface ProcedureRepository extends JpaRepository<Procedure, Long> {

    // procedureId is NOT auto-generated by the database (supplied by the application),
    // so callers must compute the next free ID before saving a new Procedure.
    @Query("SELECT COALESCE(MAX(e.procedureId), 0) FROM Procedure e")
    Long findMaxProcedureId();
}

