package medora.repository;

import medora.models.domain.ProcedureResults;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface ProcedureResultRepository extends JpaRepository<ProcedureResults, Long> {

    // result_id is NOT auto-generated by the database (supplied by the application),
    // so callers must compute the next free ID before saving a new ProcedureResults.
    @Query("SELECT COALESCE(MAX(pr.resultId), 0) FROM ProcedureResults pr")
    Long findMaxResultId();

    // UC017 – Record Procedure Outcome
    List<ProcedureResults> findByProcedureProcedureId(Long procedureId);

    // Find results for a specific medical record.
    // The schema links a medical record to a procedure (medical_record_procedures),
    // and a procedure to its results (procedure_results) — there is no direct
    // record-to-result table, so this joins through the procedure in between,
    // matching the pattern already validated for UseCase09.
    @Query("""
        SELECT pr FROM ProcedureResults pr
        WHERE pr.procedure.procedureId IN (
            SELECT mrp.procedure.procedureId FROM MedicalRecordProcedures mrp
            WHERE mrp.medicalRecord.recordId = :recordId
        )
    """)
    List<ProcedureResults> findByMedicalRecordId(@Param("recordId") Long recordId);

    // Find latest results for a procedure
    @Query("""
        SELECT pr FROM ProcedureResults pr
        WHERE pr.procedure.procedureId = :procedureId
        ORDER BY pr.resultDate DESC
    """)
    List<ProcedureResults> findLatestResultsByProcedure(@Param("procedureId") Long procedureId);

    @Query("""
        SELECT pr FROM ProcedureResults pr
        WHERE pr.procedure.procedureId = :procedureId
        AND pr.procedure.procedureId IN (
            SELECT mrp.procedure.procedureId FROM MedicalRecordProcedures mrp
            WHERE mrp.medicalRecord.recordId = :recordId
        )
    """)
    List<ProcedureResults> findByMedicalRecordAndProcedure(@Param("recordId") Long recordId, @Param("procedureId") Long procedureId);
}
