# Remote PostgreSQL environment
spring.datasource.url=jdbc:postgresql://localhost:9999/${DB_REMOTE_NAME}
spring.datasource.username=${DB_REMOTE_USERNAME}
spring.datasource.password=${DB_REMOTE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
